install.packages("here")
install.packages("skimr")
install.packages("janitor")
install.packages("dplyr")
install.packages("tidyverse")

library("here")
library("skimr")
library("janitor")
library("dplyr")
library("tidyverse")


clean_names(march_dailyActivity_merged)
clean_names(march_heartrate_seconds_merged)
clean_names(march_hourlyCalories_merged)
clean_names(march_hourlyIntensities_merged)
clean_names(march_hourlySteps_merged)
clean_names(march_minuteCaloriesNarrow_merged)
clean_names(march_minuteIntensitiesNarrow_merged)
clean_names(march_minuteMETsNarrow_merged)
clean_names(march_minuteSleep_merged)
clean_names(march_minuteStepsNarrow_merged)
clean_names(march_weightLogInfo_merged)

